CREATE TABLE Roles
(
  ROLE_ID INT NOT NULL,
  ROLE_DES VARCHAR(30) NOT NULL,
  PRIMARY KEY (ROLE_ID)
);

CREATE TABLE User
(
  USER_ID INT NOT NULL,
  USER_NAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(32) NOT NULL,
  ROLE_ID INT NOT NULL,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (ROLE_ID) REFERENCES Roles(ROLE_ID)
);

CREATE TABLE Asset
(
  ASSET_ID INT NOT NULL,
  ASSET_TYPE VARCHAR(10) NOT NULL,
  PRIMARY KEY (ASSET_ID)
);

CREATE TABLE Investor
(
  INVESTOR_USER_ID INT NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  MIDDLE_NAME VARCHAR(50),
  PAN VARCHAR(10) NOT NULL,
  COUNTRY_CODE INT NOT NULL,
  PHONE_NUMBER INT NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  START_DATE DATE NOT NULL,
  EXPIRY_DATE DATE NOT NULL,
  CURRENCY_PREFERENCE VARCHAR(3) NOT NULL,
  AMOUNT_DEPOSITED FLOAT NOT NULL,
  AMOUNT_WITHDRAWN FLOAT NOT NULL,
  BALANCE FLOAT NOT NULL,
  USER_ID INT NOT NULL,
  PRIMARY KEY (INVESTOR_USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES User(USER_ID),
  UNIQUE (PAN)
);

CREATE TABLE Company
(
  COMPANY_CODE VARCHAR(5) NOT NULL,
  ASSET_ID INT NOT NULL,
  COMPANY_TITLE VARCHAR(35) NOT NULL,
  COMPANY_SECTOR VARCHAR(20) NOT NULL,
  ASSET_ID INT NOT NULL,
  PRIMARY KEY (COMPANY_CODE),
  FOREIGN KEY (ASSET_ID) REFERENCES Asset(ASSET_ID)
);

CREATE TABLE Commodity
(
  COMMODITY_ID VARCHAR(8) NOT NULL,
  ASSET_ID INT NOT NULL,
  COMMODITY_DESC VARCHAR(32) NOT NULL,
  COMMODITY_PRICE FLOAT NOT NULL,
  COMMODITY_DATE DATE NOT NULL,
  COMMODITY_TIME DATE NOT NULL,
  ASSET_ID INT NOT NULL,
  PRIMARY KEY (COMMODITY_ID),
  FOREIGN KEY (ASSET_ID) REFERENCES Asset(ASSET_ID)
);

CREATE TABLE CompanySharesToTrade
(
  COMPANY_CODE INT NOT NULL,
  ASSET_ID INT NOT NULL,
  COMPANY_INVESTOR_ID INT NOT NULL,
  COMPANY_TURNOVER FLOAT NOT NULL,
  COMPANY_AVAILABLE_SHARES_TO_TRADE INT NOT NULL,
  COMPANY_OPENSHARE_PRICE FLOAT NOT NULL,
  CURRENCY_TYPE VARCHAR(3) NOT NULL,
  COMPANY_CODE VARCHAR(5) NOT NULL,
  ASSET_ID INT NOT NULL,
  FOREIGN KEY (COMPANY_CODE) REFERENCES Company(COMPANY_CODE),
  FOREIGN KEY (ASSET_ID) REFERENCES Asset(ASSET_ID)
);

CREATE TABLE StockPrices
(
  STOCK_COMPANY_EXCHANGE VARCHAR(8) NOT NULL,
  STOCK_CURRENT_PRICE FLOAT NOT NULL,
  STOCK_DATE DATE NOT NULL,
  STOCK_TIME DATE NOT NULL,
  STOCK_COMPANY_IPO FLOAT NOT NULL,
  STOCK_CURRENCY VARCHAR(3) NOT NULL,
  STOCK_TURNOVER FLOAT NOT NULL,
  COMPANY_CODE VARCHAR(5) NOT NULL,
  ASSET_ID INT NOT NULL,
  FOREIGN KEY (COMPANY_CODE) REFERENCES Company(COMPANY_CODE),
  FOREIGN KEY (ASSET_ID) REFERENCES Asset(ASSET_ID)
);

CREATE TABLE InvestorOperations
(
  TRADE_TYPE VARCHAR(4) NOT NULL,
  TRADE_CATEGORY VARCHAR(4) NOT NULL,
  TRADE_DATE DATE NOT NULL,
  BUYING_PRICE FLOAT NOT NULL,
  SELLING_PRICE_ FLOAT NOT NULL,
  STOCK_BUYING_CURRENCY VARCHAR(5) NOT NULL,
  STOCK_SELLING_CURRENCY VARCHAR(5) NOT NULL,
  ASSET_ID INT NOT NULL,
  USER_ID INT NOT NULL,
  FOREIGN KEY (ASSET_ID) REFERENCES Asset(ASSET_ID),
  FOREIGN KEY (USER_ID) REFERENCES User(USER_ID)
);